### ISSUE TITLE
new networking method for docker-compose 

### ISSUE THREAD

**Issue by Roboticom314** [ruffsl/ros_docker_demos#2]
In the README.md for the multicontainer version, an example is given using docker-compose. The first command (`$ docker-compose --x-networking up -d` ) doesn't seem to work with recent versions of docker.  I'm using docker-compose version 1.8.0 on ubuntu 14.04.4.

It may be that the `--x-networking` option has been deprecated in favor of the new [version 2 compose file format](https://docs.docker.com/compose/networking/).

**Comment by ruffsl** [comment]
Indeed it has. I've updated the docs on the official Docker Hub repo for ROS, but have somewhat neglected my own demo examples. If there is anything else that has become deprecated, please let me know so that when I get the time I can refresh this repo in one go.

**Comment by Roboticom314** [comment]
Will do. It's a great starting point though. 

It might be nice to add a demo here for using custom ROS package install output (from catkin_make install) in a custom docker image. Reference to setting up a private registry would be handy too. I think after that information, one could confidently create and distribute custom ROS packages in docker images.

**Comment by huamichaelchen** [comment]
First of all, great tutorial !!! Learned so much :) 
And just help others, here the version 2 docker-compose yml file that worked like a charm :) 

```
version: "2"

services:
  master:
    build: .
    container_name: master
    command:
      - roscore

  talker:
    build: .
    container_name: talker
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311"
    command: rosrun roscpp_tutorials talker

  listener:
    build: .
    container_name: listener
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: rosrun roscpp_tutorials listener
```

And here is my docker CE version
Docker version 18.09.0, build 4d60db4
